//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class BoxFilterDesc : FilterDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal BoxFilterDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.BoxFilterDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(BoxFilterDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~BoxFilterDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_BoxFilterDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public BoxFilterDesc() : this(IronSightEnginePINVOKE.new_BoxFilterDesc(), true) {
  }

  public float xwidth {
    set {
      IronSightEnginePINVOKE.BoxFilterDesc_xwidth_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.BoxFilterDesc_xwidth_get(swigCPtr);
      return ret;
    } 
  }

  public float ywidth {
    set {
      IronSightEnginePINVOKE.BoxFilterDesc_ywidth_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.BoxFilterDesc_ywidth_get(swigCPtr);
      return ret;
    } 
  }

}
