//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class D3dMeshShapeDesc : D3dShapeDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal D3dMeshShapeDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.D3dMeshShapeDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(D3dMeshShapeDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~D3dMeshShapeDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_D3dMeshShapeDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public D3dMeshShapeDesc() : this(IronSightEnginePINVOKE.new_D3dMeshShapeDesc(), true) {
  }

  public /*cstype*/ string filename {
	set {
		IronSightEnginePINVOKE.D3dMeshShapeDesc_filename_set(swigCPtr, new IronSightEnginePINVOKE.SWIGStringMarshal(value).swigCPtr);
	}

	get {
		string ret = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IronSightEnginePINVOKE.D3dMeshShapeDesc_filename_get(swigCPtr));
		return ret;
	}

  }

  public uint numvertices {
    set {
      IronSightEnginePINVOKE.D3dMeshShapeDesc_numvertices_set(swigCPtr, value);
    } 
    get {
      uint ret = IronSightEnginePINVOKE.D3dMeshShapeDesc_numvertices_get(swigCPtr);
      return ret;
    } 
  }

  public uint numfaces {
    set {
      IronSightEnginePINVOKE.D3dMeshShapeDesc_numfaces_set(swigCPtr, value);
    } 
    get {
      uint ret = IronSightEnginePINVOKE.D3dMeshShapeDesc_numfaces_get(swigCPtr);
      return ret;
    } 
  }

  public override uint GetVertexCount() {
    uint ret = IronSightEnginePINVOKE.D3dMeshShapeDesc_GetVertexCount(swigCPtr);
    return ret;
  }

  public override uint GetFaceCount() {
    uint ret = IronSightEnginePINVOKE.D3dMeshShapeDesc_GetFaceCount(swigCPtr);
    return ret;
  }

  public override D3dShapeDesc Copy() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.D3dMeshShapeDesc_Copy(swigCPtr);
    D3dShapeDesc ret = (cPtr == global::System.IntPtr.Zero) ? null : new D3dShapeDesc(cPtr, false);
    return ret;
  }

}
