//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum D3dShapeId {
  DSID_MESH,
  DSID_PLANE,
  DSID_BOX,
  DSID_SPHERE,
  DSID_CAPSULE,
  DSID_CYLINDER,
  DSID_CONE
}
