//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class D3dSphereShapeDesc : D3dShapeDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal D3dSphereShapeDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.D3dSphereShapeDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(D3dSphereShapeDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~D3dSphereShapeDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_D3dSphereShapeDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public D3dSphereShapeDesc() : this(IronSightEnginePINVOKE.new_D3dSphereShapeDesc(), true) {
  }

  public Vector3 pos {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_pos_set(swigCPtr, Vector3.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IronSightEnginePINVOKE.D3dSphereShapeDesc_pos_get(swigCPtr);
      Vector3 ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vector3(cPtr, false);
      return ret;
    } 
  }

  public float rot_y {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_rot_y_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_rot_y_get(swigCPtr);
      return ret;
    } 
  }

  public float radius {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_radius_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_radius_get(swigCPtr);
      return ret;
    } 
  }

  public uint stacks {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_stacks_set(swigCPtr, value);
    } 
    get {
      uint ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_stacks_get(swigCPtr);
      return ret;
    } 
  }

  public uint slices {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_slices_set(swigCPtr, value);
    } 
    get {
      uint ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_slices_get(swigCPtr);
      return ret;
    } 
  }

  public float theta {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_theta_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_theta_get(swigCPtr);
      return ret;
    } 
  }

  public float phi {
    set {
      IronSightEnginePINVOKE.D3dSphereShapeDesc_phi_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_phi_get(swigCPtr);
      return ret;
    } 
  }

  public override uint GetVertexCount() {
    uint ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_GetVertexCount(swigCPtr);
    return ret;
  }

  public override uint GetFaceCount() {
    uint ret = IronSightEnginePINVOKE.D3dSphereShapeDesc_GetFaceCount(swigCPtr);
    return ret;
  }

  public override D3dShapeDesc Copy() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.D3dSphereShapeDesc_Copy(swigCPtr);
    D3dShapeDesc ret = (cPtr == global::System.IntPtr.Zero) ? null : new D3dShapeDesc(cPtr, false);
    return ret;
  }

}
