//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class DirectIpt : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DirectIpt(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DirectIpt obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DirectIpt() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_DirectIpt(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public DirectIpt() : this(IronSightEnginePINVOKE.new_DirectIpt__SWIG_0(), true) {
  }

  public DirectIpt(SWIGTYPE_p_IDirectIpt src) : this(IronSightEnginePINVOKE.new_DirectIpt__SWIG_1(SWIGTYPE_p_IDirectIpt.getCPtr(src)), true) {
  }

  public SWIGTYPE_p_IDirectIpt __deref__() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.DirectIpt___deref__(swigCPtr);
    SWIGTYPE_p_IDirectIpt ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_IDirectIpt(cPtr, false);
    return ret;
  }

}
