//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum DockType {
  DT_TOPLEFT = 0x00,
  DT_TOPCENTER = 0x01,
  DT_TOPRIGHT = 0x02,
  DT_MIDDLELEFT = 0x10,
  DT_MIDDLECENTER = 0x11,
  DT_MIDDLERIGHT = 0x12,
  DT_BOTTOMLEFT = 0x20,
  DT_BOTTOMCENTER = 0x21,
  DT_BOTTOMRIGHT = 0x22
}
