//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class EnginePtr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EnginePtr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EnginePtr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EnginePtr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_EnginePtr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public EnginePtr() : this(IronSightEnginePINVOKE.new_EnginePtr__SWIG_0(), true) {
  }

  public EnginePtr(Engine src) : this(IronSightEnginePINVOKE.new_EnginePtr__SWIG_1(Engine.getCPtr(src)), true) {
  }

  public Engine __deref__() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.EnginePtr___deref__(swigCPtr);
    Engine ret = (cPtr == global::System.IntPtr.Zero) ? null : new Engine(cPtr, false);
    return ret;
  }

  public System.IntPtr GetHInstance() {
		System.IntPtr cPtr = IronSightEnginePINVOKE.EnginePtr_GetHInstance(swigCPtr);
		return cPtr;
	}

  public bool FindDLL(/*cstype*/ string dllname, SWIGTYPE_p_p_char missingdllname) {
    bool ret = IronSightEnginePINVOKE.EnginePtr_FindDLL(swigCPtr, new IronSightEnginePINVOKE.SWIGStringMarshal(dllname).swigCPtr, SWIGTYPE_p_p_char.getCPtr(missingdllname));
    return ret;
  }

  public void GetConsolePtr(Console execle) {
    IronSightEnginePINVOKE.EnginePtr_GetConsolePtr(swigCPtr, Console.getCPtr(execle));
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Result RegisterWinClass(SWIGTYPE_p_String classname, SWIGTYPE_p_HBRUSH bgbrush, bool ismdichildclass, SWIGTYPE_p_HICON icon, SWIGTYPE_p_HICON icon_small) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_0(swigCPtr, SWIGTYPE_p_String.getCPtr(classname), SWIGTYPE_p_HBRUSH.getCPtr(bgbrush), ismdichildclass, SWIGTYPE_p_HICON.getCPtr(icon), SWIGTYPE_p_HICON.getCPtr(icon_small)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterWinClass(SWIGTYPE_p_String classname, SWIGTYPE_p_HBRUSH bgbrush, bool ismdichildclass, SWIGTYPE_p_HICON icon) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_1(swigCPtr, SWIGTYPE_p_String.getCPtr(classname), SWIGTYPE_p_HBRUSH.getCPtr(bgbrush), ismdichildclass, SWIGTYPE_p_HICON.getCPtr(icon)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterWinClass(SWIGTYPE_p_String classname, SWIGTYPE_p_HBRUSH bgbrush, bool ismdichildclass) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_2(swigCPtr, SWIGTYPE_p_String.getCPtr(classname), SWIGTYPE_p_HBRUSH.getCPtr(bgbrush), ismdichildclass), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterWinClass(SWIGTYPE_p_String classname, SWIGTYPE_p_HBRUSH bgbrush) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_3(swigCPtr, SWIGTYPE_p_String.getCPtr(classname), SWIGTYPE_p_HBRUSH.getCPtr(bgbrush)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterWinClass(SWIGTYPE_p_String classname) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_4(swigCPtr, SWIGTYPE_p_String.getCPtr(classname)), true);
		//
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterWinClass() {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterWinClass__SWIG_5(swigCPtr), true);
		//
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result RegisterCustomWndProc(SWIGTYPE_p_CUSTOMWNDPROC customwndproc, SWIGTYPE_p_void user) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_RegisterCustomWndProc(swigCPtr, SWIGTYPE_p_CUSTOMWNDPROC.getCPtr(customwndproc), SWIGTYPE_p_void.getCPtr(user)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result UnregisterCustomWndProc(SWIGTYPE_p_CUSTOMWNDPROC customwndproc) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_UnregisterCustomWndProc(swigCPtr, SWIGTYPE_p_CUSTOMWNDPROC.getCPtr(customwndproc)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public void UnregisterWinClass(SWIGTYPE_p_String classname) {
    IronSightEnginePINVOKE.EnginePtr_UnregisterWinClass__SWIG_0(swigCPtr, SWIGTYPE_p_String.getCPtr(classname));
  }

  public void UnregisterWinClass() {
    IronSightEnginePINVOKE.EnginePtr_UnregisterWinClass__SWIG_1(swigCPtr);
  }

  public bool IsWinClassRegistered(SWIGTYPE_p_String classname) {
    bool ret = IronSightEnginePINVOKE.EnginePtr_IsWinClassRegistered(swigCPtr, SWIGTYPE_p_String.getCPtr(classname));
    return ret;
  }

  public Result Run(InitFunc initfunc, InitFunc postinitfunc, CyclicFunc cyclicfunc, QuitFunc quitfunc) {
    RefDelegate initfuncwrapper = delegate() {
      return Result.getCPtr(initfunc()).Handle;
    };
    RefDelegate postinitfuncwrapper = delegate() {
      return Result.getCPtr(initfunc()).Handle;
    };
    RefDelegate cyclicfuncwrapper = delegate() {
      return System.IntPtr.Zero;
    };
    RefDelegate quitfuncwrapper = delegate() {
      return System.IntPtr.Zero;
    };
    {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_Run(swigCPtr, initfuncwrapper, postinitfuncwrapper, cyclicfuncwrapper, quitfuncwrapper), true);
		//
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}
  }

  public void ChangeCyclicFunc(CyclicFunc newcyclicfunc) {
    RefDelegate newcyclicfuncwrapper = delegate() {
      return System.IntPtr.Zero;
    };
    {
      IronSightEnginePINVOKE.EnginePtr_ChangeCyclicFunc(swigCPtr, newcyclicfuncwrapper);
    }
  }

  public bool Work() {
    bool ret = IronSightEnginePINVOKE.EnginePtr_Work(swigCPtr);
    return ret;
  }

  public bool Wait() {
    bool ret = IronSightEnginePINVOKE.EnginePtr_Wait(swigCPtr);
    return ret;
  }

  public void WakeUp() {
    IronSightEnginePINVOKE.EnginePtr_WakeUp(swigCPtr);
  }

  public Result CreateTimer(SWIGTYPE_p_TIMERELAPSED_CALLBACK timercbk, uint interval, bool autoreset, SWIGTYPE_p_void user, SWIGTYPE_p_p_Timer tmr) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_CreateTimer(swigCPtr, SWIGTYPE_p_TIMERELAPSED_CALLBACK.getCPtr(timercbk), interval, autoreset, SWIGTYPE_p_void.getCPtr(user), SWIGTYPE_p_p_Timer.getCPtr(tmr)), true);
		//
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public Result ResetTimer(SWIGTYPE_p_Timer tmr, uint newinterval) {
		Result ret = new Result(IronSightEnginePINVOKE.EnginePtr_ResetTimer(swigCPtr, SWIGTYPE_p_Timer.getCPtr(tmr), newinterval), true);
		//
		if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
		return ret;
	}

  public void RemoveTimer(SWIGTYPE_p_Timer tmr) {
    IronSightEnginePINVOKE.EnginePtr_RemoveTimer(swigCPtr, SWIGTYPE_p_Timer.getCPtr(tmr));
  }

}
