//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ImageFilmDesc : FilmDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageFilmDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.ImageFilmDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageFilmDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageFilmDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_ImageFilmDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ImageFilmDesc() : this(IronSightEnginePINVOKE.new_ImageFilmDesc(), true) {
  }

  public /*cstype*/ string filename {
	set {
		IronSightEnginePINVOKE.ImageFilmDesc_filename_set(swigCPtr, new IronSightEnginePINVOKE.SWIGStringMarshal(value).swigCPtr);
	}

	get {
		string ret = System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IronSightEnginePINVOKE.ImageFilmDesc_filename_get(swigCPtr));
		return ret;
	}

  }

  public int xresolution {
    set {
      IronSightEnginePINVOKE.ImageFilmDesc_xresolution_set(swigCPtr, value);
    } 
    get {
      int ret = IronSightEnginePINVOKE.ImageFilmDesc_xresolution_get(swigCPtr);
      return ret;
    } 
  }

  public int yresolution {
    set {
      IronSightEnginePINVOKE.ImageFilmDesc_yresolution_set(swigCPtr, value);
    } 
    get {
      int ret = IronSightEnginePINVOKE.ImageFilmDesc_yresolution_get(swigCPtr);
      return ret;
    } 
  }

  public bool display {
    set {
      IronSightEnginePINVOKE.ImageFilmDesc_display_set(swigCPtr, value);
    } 
    get {
      bool ret = IronSightEnginePINVOKE.ImageFilmDesc_display_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_float cropwindow {
    set {
      IronSightEnginePINVOKE.ImageFilmDesc_cropwindow_set(swigCPtr, SWIGTYPE_p_float.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IronSightEnginePINVOKE.ImageFilmDesc_cropwindow_get(swigCPtr);
      SWIGTYPE_p_float ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_float(cPtr, false);
      return ret;
    } 
  }

}
