//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ISpriteContainer : IRenderable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ISpriteContainer(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.ISpriteContainer_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ISpriteContainer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ISpriteContainer() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_ISpriteContainer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual void SetViewTransform(Matrix viewmatrix) {
    IronSightEnginePINVOKE.ISpriteContainer_SetViewTransform(swigCPtr, Matrix.getCPtr(viewmatrix));
  }

  public virtual void SetIdentityViewTransform() {
    IronSightEnginePINVOKE.ISpriteContainer_SetIdentityViewTransform(swigCPtr);
  }

  public virtual void SetCameraViewTransform() {
    IronSightEnginePINVOKE.ISpriteContainer_SetCameraViewTransform(swigCPtr);
  }

  public virtual void SetProjectionTransform(Matrix projmatrix) {
    IronSightEnginePINVOKE.ISpriteContainer_SetProjectionTransform(swigCPtr, Matrix.getCPtr(projmatrix));
  }

  public virtual void SetIdentityProjectionTransform() {
    IronSightEnginePINVOKE.ISpriteContainer_SetIdentityProjectionTransform(swigCPtr);
  }

  public virtual void SetCameraProjectionTransform() {
    IronSightEnginePINVOKE.ISpriteContainer_SetCameraProjectionTransform(swigCPtr);
  }

  public virtual void Begin() {
    IronSightEnginePINVOKE.ISpriteContainer_Begin(swigCPtr);
  }

  public virtual void DrawSpriteImmediate(Sprite sprite) {
    IronSightEnginePINVOKE.ISpriteContainer_DrawSpriteImmediate(swigCPtr, Sprite.getCPtr(sprite));
  }

  public virtual void End() {
    IronSightEnginePINVOKE.ISpriteContainer_End(swigCPtr);
  }

  public virtual void DrawSpriteDelayed(Sprite sprite) {
    IronSightEnginePINVOKE.ISpriteContainer_DrawSpriteDelayed(swigCPtr, Sprite.getCPtr(sprite));
  }

  public virtual void Release() {
    IronSightEnginePINVOKE.ISpriteContainer_Release(swigCPtr);
  }

}
