//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LowDiscrepancySamplerDesc : SamplerDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal LowDiscrepancySamplerDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.LowDiscrepancySamplerDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LowDiscrepancySamplerDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LowDiscrepancySamplerDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_LowDiscrepancySamplerDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public LowDiscrepancySamplerDesc() : this(IronSightEnginePINVOKE.new_LowDiscrepancySamplerDesc(), true) {
  }

  public int pixelsamples {
    set {
      IronSightEnginePINVOKE.LowDiscrepancySamplerDesc_pixelsamples_set(swigCPtr, value);
    } 
    get {
      int ret = IronSightEnginePINVOKE.LowDiscrepancySamplerDesc_pixelsamples_get(swigCPtr);
      return ret;
    } 
  }

}
