//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PathSurfaceIntegratorDesc : SurfaceIntegratorDesc {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PathSurfaceIntegratorDesc(global::System.IntPtr cPtr, bool cMemoryOwn) : base(IronSightEnginePINVOKE.PathSurfaceIntegratorDesc_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PathSurfaceIntegratorDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PathSurfaceIntegratorDesc() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_PathSurfaceIntegratorDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public PathSurfaceIntegratorDesc() : this(IronSightEnginePINVOKE.new_PathSurfaceIntegratorDesc(), true) {
  }

  public int maxdepth {
    set {
      IronSightEnginePINVOKE.PathSurfaceIntegratorDesc_maxdepth_set(swigCPtr, value);
    } 
    get {
      int ret = IronSightEnginePINVOKE.PathSurfaceIntegratorDesc_maxdepth_get(swigCPtr);
      return ret;
    } 
  }

}
