//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RayTracer : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RayTracer(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RayTracer obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RayTracer() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_RayTracer(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public RayTracer() : this(IronSightEnginePINVOKE.new_RayTracer__SWIG_0(), true) {
  }

  public RayTracer(SWIGTYPE_p_IRayTracer src) : this(IronSightEnginePINVOKE.new_RayTracer__SWIG_1(SWIGTYPE_p_IRayTracer.getCPtr(src)), true) {
  }

  public SWIGTYPE_p_IRayTracer __deref__() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.RayTracer___deref__(swigCPtr);
    SWIGTYPE_p_IRayTracer ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_IRayTracer(cPtr, false);
    return ret;
  }

}
