//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SQLite : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SQLite(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SQLite obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SQLite() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_SQLite(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public SQLite() : this(IronSightEnginePINVOKE.new_SQLite__SWIG_0(), true) {
  }

  public SQLite(SWIGTYPE_p_ISQLite src) : this(IronSightEnginePINVOKE.new_SQLite__SWIG_1(SWIGTYPE_p_ISQLite.getCPtr(src)), true) {
  }

  public SWIGTYPE_p_ISQLite __deref__() {
    global::System.IntPtr cPtr = IronSightEnginePINVOKE.SQLite___deref__(swigCPtr);
    SWIGTYPE_p_ISQLite ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ISQLite(cPtr, false);
    return ret;
  }

}
