//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Vector2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_Vector2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

	public static Vector2 operator+(Vector2 v0, Vector2 v1)
	{
		return v0.add(v1);
	}

  public float x {
    set {
      IronSightEnginePINVOKE.Vector2_x_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.Vector2_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      IronSightEnginePINVOKE.Vector2_y_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.Vector2_y_get(swigCPtr);
      return ret;
    } 
  }

  public Vector2() : this(IronSightEnginePINVOKE.new_Vector2__SWIG_0(), true) {
  }

  public Vector2(Vector2 arg0) : this(IronSightEnginePINVOKE.new_Vector2__SWIG_1(Vector2.getCPtr(arg0)), true) {
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector2(float x, float y) : this(IronSightEnginePINVOKE.new_Vector2__SWIG_2(x, y), true) {
  }

  private Vector2 add(Vector2 summand) {
    Vector2 ret = new Vector2(IronSightEnginePINVOKE.Vector2_add(swigCPtr, Vector2.getCPtr(summand)), true);
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
