//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Vector3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vector3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vector3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vector3() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_Vector3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public float x {
    set {
      IronSightEnginePINVOKE.Vector3_x_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.Vector3_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      IronSightEnginePINVOKE.Vector3_y_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.Vector3_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      IronSightEnginePINVOKE.Vector3_z_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.Vector3_z_get(swigCPtr);
      return ret;
    } 
  }

  public Vector3() : this(IronSightEnginePINVOKE.new_Vector3__SWIG_0(), true) {
  }

  public Vector3(Vector3 arg0) : this(IronSightEnginePINVOKE.new_Vector3__SWIG_1(Vector3.getCPtr(arg0)), true) {
    if (IronSightEnginePINVOKE.SWIGPendingException.Pending) throw IronSightEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public Vector3(float x, float y, float z) : this(IronSightEnginePINVOKE.new_Vector3__SWIG_2(x, y, z), true) {
  }

  public Vector3(SWIGTYPE_p_float xyz) : this(IronSightEnginePINVOKE.new_Vector3__SWIG_3(SWIGTYPE_p_float.getCPtr(xyz)), true) {
  }

}
