//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class VolumeIntegratorDesc : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal VolumeIntegratorDesc(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VolumeIntegratorDesc obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VolumeIntegratorDesc() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IronSightEnginePINVOKE.delete_VolumeIntegratorDesc(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public PbrtVolumeIntegratorId id {
    get {
      PbrtVolumeIntegratorId ret = (PbrtVolumeIntegratorId)IronSightEnginePINVOKE.VolumeIntegratorDesc_id_get(swigCPtr);
      return ret;
    } 
  }

  public float stepsize {
    set {
      IronSightEnginePINVOKE.VolumeIntegratorDesc_stepsize_set(swigCPtr, value);
    } 
    get {
      float ret = IronSightEnginePINVOKE.VolumeIntegratorDesc_stepsize_get(swigCPtr);
      return ret;
    } 
  }

}
