//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Console : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Console(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Console obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Console() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ISMathPINVOKE.delete_Console(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Console() : this(ISMathPINVOKE.new_Console__SWIG_0(), true) {
  }

  public Console(SWIGTYPE_p_Console src) : this(ISMathPINVOKE.new_Console__SWIG_1(SWIGTYPE_p_Console.getCPtr(src)), true) {
  }

  public SWIGTYPE_p_Console __deref__() {
    global::System.IntPtr cPtr = ISMathPINVOKE.Console___deref__(swigCPtr);
    SWIGTYPE_p_Console ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Console(cPtr, false);
    return ret;
  }

  public void Print(/*cstype*/ string message) {
    ISMathPINVOKE.Console_Print__SWIG_0(swigCPtr, new ISMathPINVOKE.SWIGStringMarshal(message).swigCPtr);
  }

  public void Print(int message) {
    ISMathPINVOKE.Console_Print__SWIG_1(swigCPtr, message);
  }

  public void Print(double message) {
    ISMathPINVOKE.Console_Print__SWIG_2(swigCPtr, message);
  }

  public void PrintLine(/*cstype*/ string message) {
    ISMathPINVOKE.Console_PrintLine__SWIG_0(swigCPtr, new ISMathPINVOKE.SWIGStringMarshal(message).swigCPtr);
  }

  public void PrintLine(int message) {
    ISMathPINVOKE.Console_PrintLine__SWIG_1(swigCPtr, message);
  }

  public void PrintLine(double message) {
    ISMathPINVOKE.Console_PrintLine__SWIG_2(swigCPtr, message);
  }

  public void PrintD3D(/*cstype*/ string message) {
    ISMathPINVOKE.Console_PrintD3D__SWIG_0(swigCPtr, new ISMathPINVOKE.SWIGStringMarshal(message).swigCPtr);
  }

  public void PrintD3D(int message) {
    ISMathPINVOKE.Console_PrintD3D__SWIG_1(swigCPtr, message);
  }

  public void PrintD3D(double message) {
    ISMathPINVOKE.Console_PrintD3D__SWIG_2(swigCPtr, message);
  }

  public void Release() {
    ISMathPINVOKE.Console_Release(swigCPtr);
  }

}
