//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.5
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Direct3D : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Direct3D(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Direct3D obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Direct3D() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ISMathPINVOKE.delete_Direct3D(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Direct3D() : this(ISMathPINVOKE.new_Direct3D__SWIG_0(), true) {
  }

  public Direct3D(SWIGTYPE_p_IDirect3D src) : this(ISMathPINVOKE.new_Direct3D__SWIG_1(SWIGTYPE_p_IDirect3D.getCPtr(src)), true) {
  }

  public SWIGTYPE_p_IDirect3D __deref__() {
    global::System.IntPtr cPtr = ISMathPINVOKE.Direct3D___deref__(swigCPtr);
    SWIGTYPE_p_IDirect3D ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_IDirect3D(cPtr, false);
    return ret;
  }

}
